### PR TITLE
Fix performance

### LINKED ISSUE #10: Side effect
```
local checks = require('checks')

local function foo(x)
    print(x)
    checks({})
    print(x)
end

foo(nil)
```

output:

```
nil
table: 0x010860e2c8
```

So the checks changes the passed value.

### PR DESCRIPTION
**Pull request by rosik**
1) Checking table type qualifiers does not change any arguments now
(incompatible change, to be released as 3.0.0)
Close #10
 
2) Optimize out creation of temporary tables and strings
* operations with varg `{...}` replaced with `select(...)` functions
* don't check full type name with regex
* don't use string.format until the moment the error is going to be raised

### CODE REVIEW

File: checks.lua [hunk 1]
```diff
@@ -1,130 +1,163 @@
...
         return true
     end
 
-    local valid_types = {}
-    for typ in expected_type:gmatch('[^|?]+') do
-        valid_types[typ] = true
+    local checker = _G.checkers[expected_type]
+    if type(checker) == 'function' and checker(value) == true then
+        return true
     end
```
Comment (ASverdlov) [inline checks.lua]: `return false` at the end?

**Comment by ASverdlov** [comment]
Did you measure the difference in timings on perftests before and after your optimizations?

**Comment by rosik** [comment]
> Did you measure the difference in timings on perftests before and after your optimizations?

Here are results on my laptop. What I called v3.0.0 is actually this PR

image
