### PR TITLE
Fix compatibility with LuaJIT

### LINKED ISSUE #30: checks module cannot be used in LuaJIT
Tarantool's checks module is better version of the original [checks](https://luarocks.org/modules/luarocks/checks).
However it is not possible to use Tarantool's checks in LuaJIT or any other Lua interpreter, because `checks.lua` has 
statements that require Box object (`checkers.tuple = box.tuple.is`), rely on existence of `struct tt_uuid` (`local uuid_t = ffi.typeof('struct tt_uuid') `). I would hide all Tarantool specific things under condition is_tarantool().

### PR DESCRIPTION
**Pull request by ligurio**
Tarantool's checks module is better version of the original checks.
However it is not possible to use Tarantool's checks in LuaJIT or any
other Lua interpreter, because checks.lua has statements that require
box object, rely on existence of C-struct tt_uuid. This path fixes
compatibility with LuaJIT.

Fixes #30

### CODE REVIEW

File: checks.lua [hunk 1]
```diff
@@ -6,6 +6,14 @@ local _qualifiers_cache = {
     -- },
 }
 
+local function is_tarantool()
+    local rc = false
+    if _G['_TARANTOOL'] ~= nil then
+        rc = true
+    end
+    return rc
```
Comment (olegrok) [inline checks.lua:14]: It could be simplified to `return _G['_TARANTOOL'] ~= nil`

File: checks.lua [hunk 2]
```diff
@@ -226,17 +234,21 @@ function checkers.int64(arg)
     return false
 end
 
-checkers.tuple = box.tuple.is
+if is_tarantool() == true then
+    checkers.tuple = box.tuple.is
+end
```
Comment (olegrok) [inline checks.lua:239]: I suggest to move all Tarantool-specific stuff to single place

**Review by olegrok — COMMENTED** [review]
Thanks for your patch. Do you really need it? It it's so it would be great to add some tests for plain Lua/LuaJIT.

**Comment by ligurio** [comment]
> Thanks for your patch. Do you really need it? It it's so it would be great to add some tests for plain Lua/LuaJIT.

Yes. I like Tarantool's checks and use it as much as possible, even in my own Lua module. Original checks is a bit outdated, so I cannot use it.

File: checks.lua (hunk 1 above)
Comment (ligurio) [reply checks.lua:14]: FIxed.

File: checks.lua (hunk 2 above)
Comment (ligurio) [reply checks.lua]: Done.

**Comment by olegrok** [comment]
> tests require Tarantool because uses builtin TAP module.

I can't consider this as an issue. Anyway to test this module you need to build LuaJIT from source (I suppose there is no appropriate action in github marketplace). Then in the same way you could copy-paste "tap" module sources from Tarantool repository. (It should be self-sufficient).

**Review by olegrok — APPROVED** [review]

**Comment by Totktonada** [comment]
> Original checks is a bit outdated, so I cannot use it.

Just curious, what is the problem?

I would also highlight that the original checks is written on C to less impact performance (from Fabien Fleutot words).

**Comment by ligurio** [comment]
> Original checks is a bit outdated, so I cannot use it.
>> Just curious, what is the problem?

I cannot remember the problem itself, but it was absent in Tarantool's fork so I haven't digged to it..
abandoned

**Comment by ligurio** [comment]
closed accidentally

**Comment by Totktonada** [comment]
No-no, I was not against the change, just asking for details. If you have no, okay.

File: checks.lua [hunk 3]
```diff
@@ -226,17 +230,19 @@ function checkers.int64(arg)
...
 local has_decimal, decimal = pcall(require, 'decimal')
 if has_decimal and decimal.is_decimal then
     checkers.decimal = decimal.is_decimal
 end
 
--- https://github.com/tarantool/tarantool/blob/7682d34162be34648172d91008e9185301bce8f6/src/lua/uuid.lua#L29
-local uuid_t = ffi.typeof('struct tt_uuid')
-function checkers.uuid(arg)
-    return ffi.istype(uuid_t, arg)
+if is_tarantool() == true then
```
Comment (Totktonada) [inline checks.lua:238]: If the idea is to move all tatantool specific checkers under this if statement, I would also move decimal here. Or define `has_<...>` variables for tuple and uuid. Now we use different approaches here and there.

(As for me, check, whether a feature is present is better than check whether we're on tarantool.)

Comment (ligurio) [reply checks.lua:238]: Yes, I know that decimal is a tarantool-specific data type. But current approach works fine for support luajit and tarantool and thus fixes a problem.

File: .github/workflows/test.yml [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+          tarantool-version: ${{ matrix.tarantool }}
+
+      - name: Run regression testing
+        run: tarantool ./test.lua
+
+      - name: Setup LuaJIT
+        run: sudo apt install -y luajit
+
+      - name: Load checks module in LuaJIT
+        run: luajit -l checks
```
Comment (olegrok) [inline .github/workflows/test.yml:27]: I guess this part will be called for each version of Tarantool. But it's enough to do it only once.

Comment (ligurio) [reply .github/workflows/test.yml:33]: Command takes about 2ms for execution, but ok I'll move it to a separate job.

File: .github/workflows/test.yml [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+jobs:
+  test-tarantool:
+    strategy:
+      fail-fast: false
+      matrix:
+        tarantool: ['1.10', '2.5', '2.6', '2.7', '2.8']
+
+    runs-on: [ubuntu-latest]
+    steps:
+      - uses: actions/checkout@master
```
Comment (ylobankov) [inline .github/workflows/test.yml:15]: Why do you use `master`? It may be unstable and the reason for the failure of this workflow.

File: .github/workflows/test.yml [hunk 6]
```diff
@@ -0,0 +1,38 @@
+name: Test
+
+on:
+  push:
```
Comment (ylobankov) [inline .github/workflows/test.yml:4]: Should we add `pull_request` and `workflow_dispatch` triggers?

File: .github/workflows/test.yml [hunk 7]
```diff
@@ -0,0 +1,38 @@
+name: Test
```
Comment (ylobankov) [inline .github/workflows/test.yml:1]: Should we name the workflow file and workflow itself like `fast_testing` or `testing`?

Comment (ligurio) [reply .github/workflows/test.yml:1]: `test` is more than enough.

File: .github/workflows/test.yml (hunk 5 above)
Comment (ligurio) [reply .github/workflows/test.yml:15]: Because `master` is a current development branch.

File: checks.lua (hunk 3 above)
Comment (ylobankov) [reply checks.lua:238]: Looks like `if is_tarantool() then ...` should work.

File: .github/workflows/test.yml (hunk 6 above)
Comment (ligurio) [reply .github/workflows/test.yml:4]: I have added a minimal workflow to revive a testing in check's project. If you have an energy and spare time, you can polish suggested workflow for better state.

File: .github/workflows/test.yml (hunk 5 above)
Comment (ylobankov) [reply .github/workflows/test.yml:15]: The `master` branch may be unstable. Why not `v2` that is the recommended version https://github.com/actions/checkout/tree/master#usage ?

File: .github/workflows/test.yml (hunk 6 above)
Comment (ylobankov) [reply .github/workflows/test.yml:4]: Ok, no problem, we can add it later.

**Review by olegrok — APPROVED** [review]
LGTM after this comment will be resolved https://github.com/tarantool/checks/pull/31/files#r751086444

File: .github/workflows/test.yml (hunk 5 above)
Comment (ligurio) [reply .github/workflows/test.yml:15]: Sorry, missed your comment. I haven't found any difference for v1 and v2. Could you elaborate?
P.S. I'm not proficient in YAML programming, so your help would be appreciated.

Comment (ligurio) [reply .github/workflows/test.yml:15]: DDL uses `actions/checkout@master` for about a year without any problems, see https://github.com/tarantool/ddl/commit/4f5239a73edc7c310c0a5b7688355370b185f3ff#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R16

Comment (ylobankov) [reply .github/workflows/test.yml:15]: Ok, but it doesn't mean that we will have no problems in the future ;) The `master` branch may get poor-tested changes with a high probability, of course, `v2` also may,  but it's still considered as a stable version. Anyway, I think it is not a big deal and we can fix it in some follow-up patches.

Comment (Totktonada) [reply .github/workflows/test.yml:15]: It is general recommendation for using actions. In fact, after some time, when GitHub suggests `@v1`, `@v2` and so on, they start to suggest to stick on particular commit due to security reasons (a tag can be repushed). However that looks a bit weird, so I would prefer to stick on a tag, when security is not critical.
